version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: formpilot_client
    restart: always
    environment:
      REACT_APP_API_URL: "https://6ekqt6qgs1.execute-api.us-east-1.amazonaws.com/dev/api"
    ports:
      - "3000:3000"
    volumes:
      - ./client/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
    command: ["npm", "start"]
